#!/bin/bash

# LINE Bot Testing Script
# ใช้สำหรับทดสอบการเชื่อมต่อ LINE

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 LINE Bot Integration Testing"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ตัวอย่าง Group ID (จะได้หลังจากบอทเข้ากลุ่ม)
GROUP_ID="your_group_id_here"
ACCESS_TOKEN="your_line_channel_access_token_here"

echo "📝 วิธี 1: ส่งข้อความผ่าน cURL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "curl -X POST http://localhost:3001/api/send-line-notification \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"groupId\":\"$GROUP_ID\","
echo "    \"message\":\"สวัสดีจากระบบ GUNPJ\","
echo "    \"taskTitle\":\"Task Update\","
echo "    \"assignee\":\"John Doe\""
echo "  }'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📝 วิธี 2: ส่งข้อความผ่าน Frontend API"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "const response = await fetch('/api/send-line-notification', {"
echo "  method: 'POST',"
echo "  headers: { 'Content-Type': 'application/json' },"
echo "  body: JSON.stringify({"
echo "    groupId: '$GROUP_ID',"
echo "    message: 'Task completed!',"
echo "    taskTitle: 'Design Database',"
echo "    assignee: 'John Doe'"
echo "  })"
echo "});"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📝 วิธี 3: ใช้ Webhook เมื่อสร้าง/อัพเดท Task"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "เมื่อสร้าง Task ใหม่ เซิร์ฟเวอร์จะส่ง webhook ไปยัง LINE Group"
echo "ข้อมูลจาก Task จะถูกแปลงเป็นข้อความ LINE อัตโนมัติ"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "⚠️  ขั้นตอนการตั้งค่า:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. สร้าง LINE Channel ที่ https://developers.line.biz"
echo "2. ได้ Channel Access Token จาก Developers Console"
echo "3. ใส่ token ใน .env.local"
echo "4. เพิ่มบอทเข้ากลุ่ม LINE"
echo "5. ทดสอบการส่งข้อความ"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📊 ตรวจสอบเซิร์ฟเวอร์:"
echo "curl http://localhost:3001/api/health"
echo ""
